#include "colors.h"

// CONTROLS
  // buttons and switches
#define VISUALIZER_POWER_SWITCH 9
#define LIGHTING_MODE_PB 11
#define COLOR_MODE_PB 10
  // other
#define DEBOUNCE_DELAY 25
#define REST_DELAY 2500

// MSGEQ7 GRAPHIC EQUALIZER
  // pins
#define RESET_PIN 12
#define STROBE_PIN 13
#define LEFT_AUDIO_IN_PIN A0
#define RIGHT_AUDIO_IN_PIN A1 // Todo: A5 ???
  // other
#define NUMBER_OF_BANDS 7
#define MSGEQ7_READ_DELAY 40 // 36 minimum
#define AUDIO_NOISE 75
#define BAND_MAX_READING 1024

// NEOPIXEL (WS2812b) / VISUALIZER
  // pins
#define NEOPIXEL_PIN 8
  // other
#define NUM_PIXELS 140
#define NUM_COLUMNS NUMBER_OF_BANDS
#define NUM_ROWS 20
#define DEFAULT_BRIGHTNESS 100 // [0 - 255]
#define REDRAW_DELAY 20 // ms

// MODES
#define NUM_VISUALIZER_MODES 7
#define NUM_COLOR_MODES 6
#define NUM_COLOR_SCHEMES 4
#define MODE_CYCLE_DELAY 7000
#define COLOR_CYCLE_DELAY 25

const uint32_t COLOR_SCHEMES[][7] = {
  {RED, ELECTRIC_VIOLET, BLUE, ELECTRIC_VIOLET, RED, ELECTRIC_VIOLET, BLUE}, // default
  {RED, DARK_ORANGE, YELLOW, GREEN, BLUE, INDIGO, ELECTRIC_VIOLET}, // rainbow
  {SUPER_SAIYAN_YELLOW, RED, SUPER_SAIYAN_BLUE, SUPER_SAIYAN_YELLOW, RED, SUPER_SAIYAN_BLUE, SUPER_SAIYAN_YELLOW}, // super saiyan
  {KAME_BLUE, KAME_BLUE, KAME_ORANGE, KAME_ORANGE, KAME_ORANGE, KAME_BLUE, KAME_BLUE}, // kame senin
};
